[2024-11-21T09:26:03.987+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T09:26:04.022+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: university_ranking_etl.extract scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-21T09:26:04.038+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: university_ranking_etl.extract scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-21T09:26:04.039+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-21T09:26:04.062+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-11-20 00:00:00+00:00
[2024-11-21T09:26:04.076+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T09:26:04.079+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-11-21T09:26:04.087+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'university_ranking_etl', 'extract', 'scheduled__2024-11-20T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_***.py', '--cfg-path', '/tmp/tmp6iyiejr2']
[2024-11-21T09:26:04.089+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask extract
[2024-11-21T09:26:04.229+0000] {task_command.py:467} INFO - Running <TaskInstance: university_ranking_etl.extract scheduled__2024-11-20T00:00:00+00:00 [running]> on host 665f1ae1d9ef
[2024-11-21T09:26:04.581+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='university_ranking_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-20T00:00:00+00:00'
[2024-11-21T09:26:04.592+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T09:26:04.593+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T09:26:04.594+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-11-21 09:26:04.023846+00:00
[2024-11-21T09:26:04.595+0000] {logging_mixin.py:190} INFO - Dag name:university_ranking_etl and current dag run status:running
[2024-11-21T09:26:04.599+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T09:26:04.606+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-11-21T09:26:05.498+0000] {logger.py:11} INFO - WebDriver version 124.0.6367.207 selected
[2024-11-21T09:26:05.512+0000] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.207/linux64/chromedriver-linux64.zip
[2024-11-21T09:26:05.521+0000] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.207/linux64/chromedriver-linux64.zip
[2024-11-21T09:26:06.013+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-11-21T09:26:08.618+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/124.0.6367.60]
[2024-11-21T09:26:08.636+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 18, in extract
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(driver_version="124.0.6367.60").install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/124.0.6367.60/chromedriver-linux64/chromedriver unexpectedly exited. Status code was: 127

[2024-11-21T09:26:08.696+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T09:26:08.697+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 09:26:04.023846+00:00 end:2024-11-21 09:26:08.691487+00:00 duration:4.667641
[2024-11-21T09:26:08.698+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: university_ranking_etl> dagrun:<DagRun university_ranking_etl @ 2024-11-20 00:00:00+00:00: scheduled__2024-11-20T00:00:00+00:00, state:running, queued_at: 2024-11-21 09:25:45.300511+00:00. externally triggered: False>
[2024-11-21T09:26:08.699+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.wdm/drivers/chromedriver/linux64/124.0.6367.60/chromedriver-linux64/chromedriver unexpectedly exited. Status code was: 127
[2024-11-21T09:26:08.700+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=university_ranking_etl, task_id=extract, run_id=scheduled__2024-11-20T00:00:00+00:00, execution_date=20241120T000000, start_date=20241121T092604, end_date=20241121T092608
[2024-11-21T09:26:08.779+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T09:26:08.780+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task extract (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/124.0.6367.60/chromedriver-linux64/chromedriver unexpectedly exited. Status code was: 127
; 78)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 18, in extract
    driver = webdriver.Chrome(service=Service(ChromeDriverManager(driver_version="124.0.6367.60").install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/124.0.6367.60/chromedriver-linux64/chromedriver unexpectedly exited. Status code was: 127

[2024-11-21T09:26:08.857+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T09:26:08.958+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T09:26:08.963+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
